// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220712001550_Modificando")]
    partial class Modificando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Parcial2.Models.Verduras", b =>
                {
                    b.Property<int>("VerduraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.HasKey("VerduraId");

                    b.ToTable("Verduras");
                });

            modelBuilder.Entity("Parcial2.Models.VerdurasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerduraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitaminaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("VerduraId");

                    b.ToTable("VerdurasDetalle");
                });

            modelBuilder.Entity("Parcial2.Models.Vitaminas", b =>
                {
                    b.Property<int>("VitaminaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("TEXT");

                    b.HasKey("VitaminaId");

                    b.ToTable("Vitaminas");

                    b.HasData(
                        new
                        {
                            VitaminaId = 1,
                            Descripcion = "Vitamina C",
                            Existencia = 0.0,
                            UnidadMedida = "(mg)"
                        },
                        new
                        {
                            VitaminaId = 2,
                            Descripcion = "Betaína",
                            Existencia = 0.0,
                            UnidadMedida = "(mg)"
                        },
                        new
                        {
                            VitaminaId = 3,
                            Descripcion = "Vitamina K",
                            Existencia = 0.0,
                            UnidadMedida = "(mcg)"
                        },
                        new
                        {
                            VitaminaId = 4,
                            Descripcion = "Vitamina A ",
                            Existencia = 0.0,
                            UnidadMedida = "(mcg RAE)"
                        },
                        new
                        {
                            VitaminaId = 5,
                            Descripcion = "Vitamina E",
                            Existencia = 0.0,
                            UnidadMedida = "(mg)"
                        },
                        new
                        {
                            VitaminaId = 6,
                            Descripcion = "Ácido fólico(B9)",
                            Existencia = 0.0,
                            UnidadMedida = "(mg)"
                        });
                });

            modelBuilder.Entity("Parcial2.Models.VerdurasDetalle", b =>
                {
                    b.HasOne("Parcial2.Models.Verduras", null)
                        .WithMany("Detalle")
                        .HasForeignKey("VerduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parcial2.Models.Verduras", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
