// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parcial2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Parcial2.Models.Verduras", b =>
                {
                    b.Property<int>("VerduraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.HasKey("VerduraId");

                    b.ToTable("Verduras");
                });

            modelBuilder.Entity("Parcial2.Models.VerdurasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<int>("VerduraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitaminaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("VerduraId");

                    b.ToTable("VerdurasDetalle");
                });

            modelBuilder.Entity("Parcial2.Models.Vitaminas", b =>
                {
                    b.Property<int>("VitaminaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<double>("UnidadDeMedida")
                        .HasColumnType("REAL");

                    b.HasKey("VitaminaId");

                    b.ToTable("Vitaminas");

                    b.HasData(
                        new
                        {
                            VitaminaId = 1,
                            Descripcion = "Vitamina C (mg)",
                            UnidadDeMedida = 120.0
                        },
                        new
                        {
                            VitaminaId = 2,
                            Descripcion = "Betaína (mg)",
                            UnidadDeMedida = 1.54
                        },
                        new
                        {
                            VitaminaId = 3,
                            Descripcion = "Vitamina K (mcg)",
                            UnidadDeMedida = 390.0
                        },
                        new
                        {
                            VitaminaId = 4,
                            Descripcion = "Vitamina A (mcg RAE)",
                            UnidadDeMedida = 90.0
                        },
                        new
                        {
                            VitaminaId = 5,
                            Descripcion = "Vitamina E (mg)",
                            UnidadDeMedida = 700.0
                        },
                        new
                        {
                            VitaminaId = 6,
                            Descripcion = "Tiamina(B1) (mg)",
                            UnidadDeMedida = 0.089999999999999997
                        },
                        new
                        {
                            VitaminaId = 7,
                            Descripcion = "Choline (mg)",
                            UnidadDeMedida = 0.14999999999999999
                        },
                        new
                        {
                            VitaminaId = 8,
                            Descripcion = "Ácido fólico(B9) (mg)",
                            UnidadDeMedida = 400.0
                        },
                        new
                        {
                            VitaminaId = 9,
                            Descripcion = "Riboflavina(B2) (mg)",
                            UnidadDeMedida = 0.90000000000000002
                        },
                        new
                        {
                            VitaminaId = 10,
                            Descripcion = "Folate(B9) (μg)",
                            UnidadDeMedida = 143.0
                        });
                });

            modelBuilder.Entity("Parcial2.Models.VerdurasDetalle", b =>
                {
                    b.HasOne("Parcial2.Models.Verduras", null)
                        .WithMany("Detalle")
                        .HasForeignKey("VerduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parcial2.Models.Verduras", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
